# TODO: Consolidate and clean these settings

# in increasing level of severity: DEBUG, INFO, ERROR
log_level:                                  DEBUG

# Sliding window configurations
sliding_window:
  is_test:                                    false
  folders:
    frame_output:                             frames
    patch_output:                             patches
    annotation_output:                        json
    levedb_output:                            leveldb
    video_output:                             videos
    numpy_output:                             numpy
  frame_density:                              25
  # Dimension of patches
  output_width:                               256
  output_height:                              256
  x_stride:                                   128
  y_stride:                                   128
  scaling:
    - 0.4
    - 0.6
    - 0.8


# Caffe input
caffe_input:
  model_file:                                 "/mnt/data/logo/caffe_logo_train_iter_5000"
  prototxt_file:                              "/mnt/data/logo/logo_video.prototxt"
  # number of frames to put in one leveldb - ensure no more than 3.5GB
  num_frames_per_leveldb:                    4
  num_concurrent_leveldbs:                   2
  video_frame_number_start:                  1
  use_gpu:                                   false
  save_video_heatmap:                        true
  all_classes:
    - '0'
    - '1'
  background_classes:
    - '1'

# Post processing
post_processing:
  detector_threshold:                         0.9

# Curation
curation:
  # total patches per class = num_of_sets * num_of_patch_per_set
  num_of_sets:                                5
  num_of_patch_per_set:                       100
