
# in increasing level of severity: DEBUG, INFO, ERROR
log_level:                                  DEBUG

# Sliding window configurations
sliding_window:
  is_test:                                    false
  folders:
    frame_output:                             frames
    patch_output:                             patches
    json_output:                              json
    levedb_output:                            leveldb
    video_output:                             videos
    numpy_output:                             numpy
  frame_density:                              5
  # Dimension of patches
  output_width:                               256
  output_height:                              256
  x_stride:                                   128
  y_stride:                                   128
  scaling:
    - 0.4
    - 0.6
    - 0.8
    - 1.0
    - 1.2
    - 1.4

# Caffe input
caffe_input:
  model_file:                                 "/mnt/data/logo/caffe_logo_train_iter_5000"
  video_prototxt_file:                        "/mnt/data/logo/logo_video.prototxt"
  deploy_prototxt_file:                       "/mnt/data/logo/logo_deploy.prototxt"
  # number of frames to put in one leveldb
  num_frames_per_leveldb:                    50
  num_concurrent_leveldbs:                   2
  # leveldb might be maintained in TEMPFS - if exceed this size, pause leveldb creation
  # if want to ignore the size limit, set to zero
  max_leveldb_size_mb:                       10000
  video_frame_number_start:                  1
  use_gpu:                                   true
  save_video_heatmap:                        true
  all_classes:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  background_classes:
    - '3'

# Post processing
post_processing:
  detector_threshold:                         0.8

# Curation
curation:
  # total patches per class = num_of_sets * num_of_patch_per_set
  num_of_sets:                                5
  num_of_patch_per_set:                       100
