# TODO: Consolidate and clean these settings


# Sliding window configurations
sliding_window:
  is_test:                                    false
  folders:
    patch_output:                             patches
    annotation_output:                        json
  frame_density:                              5
  # Dimension of patches
  output_width:                               256
  output_height:                              256
  x_stride:                                   128
  y_stride:                                   128
  scaling:
    - 0.4
    - 0.6
    - 0.8
    - 1.0
    - 1.2
    - 1.4
pretrained_file: "caffe_logo_train_iter_500"
classes: [ "0", "1" ]

# Post processing
post_processing:
  background_classes:
    - '1'
  detector_threshold:                         0.9

# Curation
curation:
  # total patches per class = num_of_sets * num_of_patch_per_set
  num_of_sets:                                5
  num_of_patch_per_set:                       100
