# Khajuri Config

# in increasing level of severity: DEBUG, INFO, ERROR, CRITICAL
logging:
  log_level:                                  DEBUG
  rabbit_logger:                              false
  write_logs_to_queue:                        false

# process video config values
process_video_job:
  kheerJobId:                                1
  environment:                               'development'
  videoId:                                   1
  videoFileName:                             ''
  chiaVersionId:                             1
  baseDbFolder:                              '/mnt/tmp/lmdb'
  jsonFolder:                                'json'
  numpyFolder:                               'numpy'

# Sliding window configurations
sliding_window:
  frame_density:                              5
  frame_width:                                1280
  frame_height:                               720
  # Dimension of patches
  output_width:                               256
  output_height:                              256
  x_stride:
    - 32
    - 64
    - 64
    - 128
    - 128
  y_stride:
    - 16
    - 32
    - 64
    - 64
    - 128
  scaling:
    - 0.4
    - 0.7
    - 1.0
    - 1.3
    - 1.6

  # put in same folder as this config.yaml file - no absolute path here
  scale_decayed_factors_file:                "config_scale_decay_factors.json"

# Caffe input
caffe_input:
  model_file:                                 "/mnt/data/wc14itr/set04/runResults/caffe_logo_train_iter_5000"
  video_prototxt_file:                        "/mnt/data/wc14itr/set04/runResults/prototxt/logo_video.prototxt"

  # lmdb circular buffers - look at issue65 for setting these
  lmdb_buffer_max_size:                      6
  lmdb_buffer_min_size:                      4
  lmdb_num_frames_per_buffer:                1

  # post-processing queue size management (num of frames in queue)
  pp_queue_max_size:                         5000
  pp_queue_high_watermark:                   4000
  pp_queue_low_watermark:                    1000

  # frame number to start video processing on
  video_frame_number_start:                  1
  use_gpu:                                   true
  gpu_devices:                               
    - 0
    - 1
    - 2
    - 3

  run_caffe:                                 true
  run_postprocess:                           true
  all_classes:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '22'
    - '23'
    - '24'
    - '25'
    - '26'
    - '27'
    - '28'
    - '29'
    - '30'
    - '31'
    - '32'
    - '33'
    - '34'
    - '35'
    - '36'
    - '37'
    - '38'
    - '39'
    - '40'
    - '41'
    - '42'
    - '43'
    - '44'
    - '45'
    - '46'
    - '47'
    - '48'

  background_classes:
    - '4'
    - '15'
    - '43'
    - '44'

# Post processing
post_processing:
  detector_threshold:                         0.8
  z_dist_thresholds:
    - 0
    - 2
    - 4
  result_writers:
    json_writer:                              true
    rabbit_writer:                            false

# HDF5 storage
hdf5:
  hdf5_base_folder:                           '/var/www/kheer/public/data'

# Messaging
messaging:
  amqp_url:                                     'localhost'
  queue_names:
    vm2_kahjuri_development_video_data:         'vm2.kahjuri.development.video_data'
    vm2_khajuri_development_log:                'vm2.khajuri.development.log'
    vm2_kheer_development_clip_id_request:      'vm2.kheer.development.clip_id.request'
    vm2_kheer_development_heatmap_rpc_request:  'vm2.kheer.development.heatmap_rpc.request'
    vm2_kheer_development_localization_request: 'vm2.kheer.development.localization.request'
